name: CI

on:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t alix2022/portfolio .

      - name: push image
        run: |
              docker login -u alix2022 -p ${{secrets.REGISTRY_PASS}}
              docker push alix2022/portfolio